hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - task=g1/robot_object_ref
    - init_knots_from_ref=True
    - solver=cem
    - warm_start.incremental=True
    - solver.cfg.alpha_cov=0.25
    - solver.cfg.alpha_mean=0.95
    - solver.cfg.sigma0=0.25
    - solver.cfg.N_it=0
    - task.sim.cfg.interp_kind=pchip
    - solver.cfg.keep_frac=0.05
    - task.cfg.ref_motion_path=glob(./sbto/tasks/g1/robot-object/*original.npz)
  job:
    name: main
    chdir: null
    override_dirname: init_knots_from_ref=True,solver.cfg.N_it=0,solver.cfg.alpha_cov=0.25,solver.cfg.alpha_mean=0.95,solver.cfg.keep_frac=0.05,solver.cfg.sigma0=0.25,solver=cem,task.cfg.ref_motion_path=glob(./sbto/tasks/g1/robot-object/*original.npz),task.sim.cfg.interp_kind=pchip,task=g1/robot_object_ref,warm_start.incremental=True
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /dss/dsshome1/0F/go29van4/Workspace/sbto
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /dss/dsshome1/0F/go29van4/Workspace/sbto/sbto/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      solver: cem
      task: g1/robot_object_ref
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
task:
  _target_: sbto.tasks.g1.robot_object_ref.G1RobotObjRef
  cfg:
    _target_: sbto.tasks.g1.robot_object_ref.ConfigG1RobotObjRef
    ref_motion_path: glob("./sbto/tasks/g1/robot-object/*original.npz")
    t0: 0.0
    speedup: 1.25
    z_offset: 0.01
    t_hand_cnt_before_lift: 0.15
    t_hand_cnt_after_place: 0.15
    joint_pos_weight: 0.3
    joint_vel_weight: 0.01
    base_pos_weight: 5.0
    base_quat_weight: 1.0
    torso_pos_weight: 30.0
    torso_quat_weight: 2.0
    torso_quat_weight_terminal: 2.0
    torso_linvel_weight: 1.0
    torso_linvel_weight_terminal: 1.0
    torso_angvel_weight: 1.0
    torso_angvel_weight_terminal: 1.0
    foot_position: 15.0
    foot_orientation: 0.1
    contact_feet_weight: 0.0
    contact_force_feet_weight: 1.0e-06
    hand_position: 20.0
    hand_orientation: 0.0
    obj_pos_weight: 20.0
    obj_quat_weight: 2.0
    obj_v_weight: 1.0
    obj_w_weight: 2.0
    contact_obj_weight: 0.5
    contact_hands_weight: 0.25
    collision_obj_robot: 2.0
  sim:
    _target_: sbto.sim.sim_mj_rollout.SimMjRollout
    cfg:
      _target_: sbto.sim.sim_mj_rollout.ConfigMjRollout
      T: 500
      Nknots: 25
      interp_kind: pchip
      Nthread: -1
      _chunk_size: 2
    scaling:
      _target_: sbto.sim.action_scaling.Scaling
      name: nominal
      clip: false
    mj_scene:
      _target_: sbto.sim.scene_mj.MjScene
      cfg:
        _target_: sbto.sim.scene_mj.ConfigMjScene
        xml_scene_path: sbto/models/unitree_g1/scene_mjx_29dof_no_hands.xml
        xml_sensors_path: sbto/models/unitree_g1/sensors/tracking_w_obj.xml
        xml_contact_pairs_path: sbto/models/unitree_g1/contact_pairs/with_obj.xml
        add_body:
          largebox:
            type: body_only
            pos:
            - 0.4
            - 0.0
            - 0.1
            euler:
            - 0.0
            - 0.0
            - 0.0
          obj:
            type: box
            pos:
            - 0.0
            - 0.0
            - 0.0
            size:
            - 0.18
            - 0.18
            - 0.18
            euler:
            - 3.05
            - 0.11
            - 1.11
            mass: 0.6
            rgba:
            - 0.3
            - 0.3
            - 0.3
            - 1.0
            freejoint: true
            bodyname: largebox
            group: 1
            priority: 1
            condim: 3
            contype: 0
            conaffinity: 1
            solref:
            - 0.008
            - 1.0
            friction:
            - 0.6
            - 0.005
            - 0.0001
solver:
  _target_: sbto.solvers.cem.CEM
  cfg:
    _target_: sbto.solvers.cem.ConfigCEM
    N_samples: 1024
    N_it: 0
    elite_frac: 0.05
    keep_frac: 0.05
    alpha_mean: 0.95
    alpha_cov: 0.25
    std_incr: 0.0
    sigma0: 0.25
    quasi_random: true
    seed: 0
    sampler: normal
description: ''
save_fig: true
init_knots_from_ref: true
warm_start:
  rundir: ''
  add_cov_diag: 0.0
  N_it: 0
  multiple_shooting: false
  incremental: true
  N_max_incr: 50
  min_std_next: 0.04
