defaults:
  - task: g1/robot_object_ref
  - solver: cem
  - slurm: none
  - warm_start: incremental
  - data_processing: default
  - random: none
  - _self_

# Experiment name (will be root dir of the data)
exp_name: ""
# Description (as a suffix to rundir)
description: ""
# If a reference is provided, initial knots are taken from the reference
init_knots_from_ref: True