_target_: sbto.solvers.cbox.CBO
cfg:
  _target_: sbto.solvers.cbox.ConfigCBO
  N_samples: 1024
  N_it: 100
  beta: 1e10
  noise_model: anistropic
  delta: 0.01
  dt: 0.01
  lambda_: 1.0
  min_it_per_knot: 100
  sigma0: 0.25
  quasi_random: False
  seed: 0
  sampler: normal
