_target_: sbto.solvers.cbox_polar.CBO
cfg:
  _target_: sbto.solvers.cbox_polar.ConfigCBO
  N_samples: 1024
  N_it: 100
  beta: 1e10
  noise_model: anistropic
  delta: 0.01
  dt: 0.01
  lambda_: 1.0
  kappa: 1.0
  adaptive_kappa: true
  kappa_subsample: 128
  scalar_reg_loss_weight_neighborhood_kernel: 1.0
  flag_auto_weight: true
  min_it_per_knot: 100
  load_initial_sampling_state: True
  use_loaded_mean_only: True
  ini_cov_scale: 1.0
  ini_dist_path: ""
  sigma0: 0.25
  quasi_random: False
  seed: 0
  sampler: normal
  mixed_init_frac: 0.5
  population_init_path: ""
